IF  DB_ID('MyWebDB') IS NOT NULL
    DROP DATABASE MyWebDB;
CREATE DATABASE MyWebDB;
USE MyWebDB;

CREATE TABLE Users(
	UserID INT PRIMARY KEY IDENTITY
	,EmailAddress VARCHAR(50) NOT NULL
	,FirstName VARCHAR(50) NOT NULL
	,LastName VARCHAR(50) NOT NULL);

CREATE TABLE Products(
	ProductID INT PRIMARY KEY IDENTITY
	,ProductName VARCHAR(50) NOT NULL);

CREATE TABLE Downloads(
	DownloadID INT PRIMARY KEY IDENTITY NOT NULL
	,UserID INT FOREIGN KEY REFERENCES Users (UserID) NOT NULL
	,ProductID INT FOREIGN KEY REFERENCES Product (ProductID) NOT NULL
	,DownloadDate DATE NOT NULL
	,FileName VARCHAR(255) NOT NULL);

CREATE INDEX IX_EmailAddress
	ON Users (EmailAddress);

CREATE INDEX IX_ProductName
	ON Products (ProductName);
